version: "3.9"

services:
    server-php:
        container_name: opticaAdam_php
        build: .
        restart: unless-stopped
        ports:
            - "8001:8000"
        volumes:
            - .:/var/www/html:delegated
        networks:
            - project_network
        depends_on:
            - mariadb-server

    mariadb-server:
        container_name: opticaAdam_db
        image: mariadb:11
        restart: unless-stopped
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: proyecto
        volumes:
            - db_mysql:/var/lib/mysql
        networks:
            - project_network

volumes:
    db_mysql:

networks:
    project_network:
