nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false

    paths:
        # Configuración para todas las rutas /api/*
        '^/api/':
            # Orígenes permitidos (tu frontend Angular)
            allow_origin: [ '*' ]

            # Headers permitidos en las peticiones
            allow_headers: [ 'Content-Type', 'Authorization', 'X-Custom-Auth' ]

            # Métodos HTTP permitidos
            allow_methods: [ 'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS' ]

            # Tiempo en segundos que el navegador cachea la respuesta preflight
            max_age: 3600

        '^/':
            origin_regex: true
            allow_origin: [ '^http://localhost:[0-9]+' ]
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE' ]
            max_age: 3600
            hosts: [ '^api\.' ]


